/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: 'es' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Promoted item: product, service, good, craft, course or other.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  /**
   * Offer type. Sets the label on the public card.
   */
  kind?: ('product' | 'service' | 'good' | 'craft' | 'course' | 'other') | null;
  description?: string | null;
  /**
   * Optional. If empty or 0, it is hidden on the site.
   */
  price?: number | null;
  /**
   * Shows first in the carousel, with the Featured tag.
   */
  featured?: boolean | null;
  /**
   * Shows the Sale tag in the carousel.
   */
  promo?: boolean | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Standalone pages. Section buttons can link here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  description?: T;
  price?: T;
  featured?: T;
  promo?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * If there is no logo, the default image is shown.
   */
  logo?: (number | null) | Media;
  /**
   * If empty, the site name is used.
   */
  logoText?: string | null;
  showLogo?: boolean | null;
  showLogoText?: boolean | null;
  /**
   * SEO meta description (up to ~160 characters).
   */
  metaDescription?: string | null;
  contactEmail?: string | null;
  /**
   * URL or number, e.g. https://wa.me/54911...
   */
  whatsapp?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  linkedin?: string | null;
  pinterest?: string | null;
  colorPrimary?: string | null;
  colorSecondary?: string | null;
  colorFontPrimary?: string | null;
  fontPrimary?:
    | (
        | 'open-sans'
        | 'lato'
        | 'montserrat'
        | 'nunito'
        | 'inter'
        | 'poppins'
        | 'raleway'
        | 'work-sans'
        | 'dm-sans'
        | 'figtree'
        | 'outfit'
        | 'manrope'
        | 'playfair'
        | 'source-serif'
        | 'merriweather'
        | 'lora'
        | 'libre-baskerville'
        | 'cormorant'
        | 'fraunces'
        | 'eb-garamond'
      )
    | null;
  colorFontSecondary?: string | null;
  fontSecondary?:
    | (
        | 'open-sans'
        | 'lato'
        | 'montserrat'
        | 'nunito'
        | 'inter'
        | 'poppins'
        | 'raleway'
        | 'work-sans'
        | 'dm-sans'
        | 'figtree'
        | 'outfit'
        | 'manrope'
        | 'playfair'
        | 'source-serif'
        | 'merriweather'
        | 'lora'
        | 'libre-baskerville'
        | 'cormorant'
        | 'fraunces'
        | 'eb-garamond'
      )
    | null;
  showNav?: boolean | null;
  showNavCta?: boolean | null;
  showLangSwitch?: boolean | null;
  showHeroSearch?: boolean | null;
  searchPlaceholder?: string | null;
  navCta?: string | null;
  /**
   * If empty, the default menu is used. href: /en#faq or /en/nosotros.
   */
  navItems?:
    | {
        label: string;
        href: string;
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main, About, FAQ and Contact us are included by default. Reorder, hide or add sections.
   */
  sections?:
    | (
        | {
            showTitle?: boolean | null;
            showLead?: boolean | null;
            showCta?: boolean | null;
            showSearch?: boolean | null;
            showImage?: boolean | null;
            title?: string | null;
            lead?: string | null;
            cta?: string | null;
            ctaPage?: (number | null) | Page;
            /**
             * E.g. #contacto, #nosotros or /en/paginas/notice. If both page and URL are set, the URL is used.
             */
            ctaHref?: string | null;
            searchPlaceholder?: string | null;
            slideTransition?: ('fade' | 'slide' | 'slide-left' | 'rise' | 'zoom' | 'none') | null;
            slides?:
              | {
                  visible?: boolean | null;
                  image?: (number | null) | Media;
                  showImage?: boolean | null;
                  title?: string | null;
                  titleAlign?: ('left' | 'center' | 'right') | null;
                  titleAlignY?: ('top' | 'center' | 'bottom') | null;
                  titleSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
                  titleColor?: string | null;
                  showTitle?: boolean | null;
                  text?: string | null;
                  textAlign?: ('left' | 'center' | 'right') | null;
                  textAlignY?: ('top' | 'center' | 'bottom') | null;
                  textSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
                  textColor?: string | null;
                  showText?: boolean | null;
                  showCta?: boolean | null;
                  cta?: string | null;
                  ctaPage?: (number | null) | Page;
                  ctaAlign?: ('left' | 'center' | 'right') | null;
                  ctaAlignY?: ('top' | 'center' | 'bottom') | null;
                  ctaSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
                  ctaColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            slideDuration?: number | null;
            showSlideNav?: boolean | null;
            showInMenu?: boolean | null;
            visible?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            lead?: string | null;
            showTitle?: boolean | null;
            showLead?: boolean | null;
            showFeatured?: boolean | null;
            showPromo?: boolean | null;
            showAll?: boolean | null;
            visible?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carousel';
          }
        | {
            title?: string | null;
            text?: string | null;
            circleImages?: boolean | null;
            cards?:
              | {
                  image?: (number | null) | Media;
                  title?: string | null;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            showTitle?: boolean | null;
            visible?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about';
          }
        | {
            title?: string | null;
            faqs?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            showTitle?: boolean | null;
            visible?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            title?: string | null;
            text?: string | null;
            button?: string | null;
            showTitle?: boolean | null;
            showText?: boolean | null;
            showButton?: boolean | null;
            visible?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'talkToUs';
          }
        | {
            title?: string | null;
            showTitle?: boolean | null;
            showInMenu?: boolean | null;
            layout: 'media' | 'cards';
            cardsPerRow?: number | null;
            image?: (number | null) | Media;
            showImage?: boolean | null;
            imageAlign?: ('left' | 'right') | null;
            subtitle?: string | null;
            showSubtitle?: boolean | null;
            text?: string | null;
            showText?: boolean | null;
            showButton?: boolean | null;
            buttonLabel?: string | null;
            buttonPage?: (number | null) | Page;
            cards?:
              | {
                  visible?: boolean | null;
                  image?: (number | null) | Media;
                  imageShape?: ('square' | 'oval' | 'circle' | 'portrait' | 'landscape') | null;
                  imageAlign?: ('left' | 'center' | 'right') | null;
                  imageAlignY?: ('top' | 'center' | 'bottom') | null;
                  showImage?: boolean | null;
                  subtitle?: string | null;
                  subtitleAlign?: ('left' | 'center' | 'right') | null;
                  showSubtitle?: boolean | null;
                  text?: string | null;
                  textAlign?: ('left' | 'center' | 'justify' | 'right') | null;
                  showText?: boolean | null;
                  footer?: string | null;
                  footerAlign?: ('left' | 'center' | 'right') | null;
                  showFooter?: boolean | null;
                  buttonLabel?: string | null;
                  buttonPage?: (number | null) | Page;
                  buttonAlign?: ('left' | 'center' | 'right') | null;
                  showButton?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'extra';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  logoText?: T;
  showLogo?: T;
  showLogoText?: T;
  metaDescription?: T;
  contactEmail?: T;
  whatsapp?: T;
  instagram?: T;
  facebook?: T;
  twitter?: T;
  youtube?: T;
  tiktok?: T;
  linkedin?: T;
  pinterest?: T;
  colorPrimary?: T;
  colorSecondary?: T;
  colorFontPrimary?: T;
  fontPrimary?: T;
  colorFontSecondary?: T;
  fontSecondary?: T;
  showNav?: T;
  showNavCta?: T;
  showLangSwitch?: T;
  showHeroSearch?: T;
  searchPlaceholder?: T;
  navCta?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        visible?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              showTitle?: T;
              showLead?: T;
              showCta?: T;
              showSearch?: T;
              showImage?: T;
              title?: T;
              lead?: T;
              cta?: T;
              ctaPage?: T;
              ctaHref?: T;
              searchPlaceholder?: T;
              slideTransition?: T;
              slides?:
                | T
                | {
                    visible?: T;
                    image?: T;
                    showImage?: T;
                    title?: T;
                    titleAlign?: T;
                    titleAlignY?: T;
                    titleSize?: T;
                    titleColor?: T;
                    showTitle?: T;
                    text?: T;
                    textAlign?: T;
                    textAlignY?: T;
                    textSize?: T;
                    textColor?: T;
                    showText?: T;
                    showCta?: T;
                    cta?: T;
                    ctaPage?: T;
                    ctaAlign?: T;
                    ctaAlignY?: T;
                    ctaSize?: T;
                    ctaColor?: T;
                    id?: T;
                  };
              slideDuration?: T;
              showSlideNav?: T;
              showInMenu?: T;
              visible?: T;
              id?: T;
              blockName?: T;
            };
        carousel?:
          | T
          | {
              title?: T;
              lead?: T;
              showTitle?: T;
              showLead?: T;
              showFeatured?: T;
              showPromo?: T;
              showAll?: T;
              visible?: T;
              id?: T;
              blockName?: T;
            };
        about?:
          | T
          | {
              title?: T;
              text?: T;
              circleImages?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              image?: T;
              showTitle?: T;
              visible?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              showTitle?: T;
              visible?: T;
              id?: T;
              blockName?: T;
            };
        talkToUs?:
          | T
          | {
              title?: T;
              text?: T;
              button?: T;
              showTitle?: T;
              showText?: T;
              showButton?: T;
              visible?: T;
              id?: T;
              blockName?: T;
            };
        extra?:
          | T
          | {
              title?: T;
              showTitle?: T;
              showInMenu?: T;
              layout?: T;
              cardsPerRow?: T;
              image?: T;
              showImage?: T;
              imageAlign?: T;
              subtitle?: T;
              showSubtitle?: T;
              text?: T;
              showText?: T;
              showButton?: T;
              buttonLabel?: T;
              buttonPage?: T;
              cards?:
                | T
                | {
                    visible?: T;
                    image?: T;
                    imageShape?: T;
                    imageAlign?: T;
                    imageAlignY?: T;
                    showImage?: T;
                    subtitle?: T;
                    subtitleAlign?: T;
                    showSubtitle?: T;
                    text?: T;
                    textAlign?: T;
                    showText?: T;
                    footer?: T;
                    footerAlign?: T;
                    showFooter?: T;
                    buttonLabel?: T;
                    buttonPage?: T;
                    buttonAlign?: T;
                    showButton?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}